### ISSUE TITLE
qos is not subclassed in amqp backend

### ISSUE THREAD

**Issue by stevvooe** [ask/carrot#18] opened 2009-09-29 04:27 UTC
Amqp backend needs to implement qos method. Work around is the following:

Consumer.backend.channel.basic_qos(0, 1, False)

Monkey Patching fixes the problem as well ;)

**Comment by ask** [comment] 2009-09-29 07:36
Forgot to implement qos/flow in amqplib backend (doh). Closed by 1736aaa4b0875ea89f99a3b3b06bd2c0e36b3b7c. Thanks stevvooe!

**Closed as completed by ask** 2009-09-29 07:36 UTC

**Comment by ask** [comment] 2009-09-29 07:40
oh god! it must've been lost in some commit somewhere </excuses>

**Comment by stevvooe** [comment] 2009-09-29 21:23
No worries, but you could understand the frustration... there were several WTFs tracking this down ;). Perhaps, you should use ABCMeta with abstractmethod so you get exceptions when certain methods aren't subclassed.

Thanks for the quick fix!

**Comment by ask** [comment] 2009-09-30 07:53
Thank _you_ for finding it. I've been scratching my head for some time as well. I found the change, it was lost in a git stash actually :( 

The problem is then we have to decide how we handle the other backends (STOMP). Should we support the program semi-working with another backend, e.g. receiveing/sending messages works, but QoS doesn't. I don't know if it's a good thing, or if people should have to do try: qos() except NotImplementedError... for every backend method, I like that it fails silently in some ways, but then we can't raise exceptions on missing features either.

**Comment by ask** [comment] 2009-10-05 12:12
Ok, so I have a plan for incorporating NotImplementedErrors for missing backend functionality. In the next version (0.7.0), all base methods not implemented will raise a DeprecationWarning saying it will raise an error in 1.0.
